#cloud-config
swap:
  filename: /swap.img
  size: ${swap_bytes}
  maxsize: ${swap_bytes_max}

apt:
  package_update: true
  # Add PHP/Apache sources.
  sources:
    source1:
      source: 'ppa:ondrej/php'
    source2:
      source: 'ppa:ondrej/apache2'

runcmd:
  # Change swappiness
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf
