#cloud-config
apt:
  # Add PHP/Apache sources.
  sources:
    source1:
      source: 'ppa:ondrej/php'
    source2:
      source: 'ppa:ondrej/apache2'

packages:
  # Lamp
  - lamp-server^

  # Apache and mods
  - apache2
  - apache2-bin
  - libapache2-mod-php${php_ver}

  # Dev tools
  - composer
  - git

  # PHP extensions
  - php${php_ver}-curl
  - php${php_ver}-gd
  - php${php_ver}-mbstring
  - php${php_ver}-mysql
  - php${php_ver}-xml
  - php${php_ver}-zip


runcmd:
  # Change swappiness
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf

  # Composer
  - export HOME=/root
  - composer global require consolidation/cgr
  - echo PATH="$(composer global config home)/vendor/bin:$PATH" >> ~/.bashrc
  - . ~/.bashrc

  # Drush Launcher
  # Best practice is to require Drush on a per-project basis, see
  # https://github.com/drush-ops/drush-launcher
  # - cgr drush/drush
  - wget -O drush.phar https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
  - chmod +x drush.phar
  - mv drush.phar /usr/local/bin/drush

  # MySQL setup
  # - mysql -e 'CREATE DATABASE drupal'
  # - mysql -e 'GRANT ALL PRIVILEGES ON drupal.* TO drupal@localhost IDENTIFIED BY '\''${mysql_password}'\'

  # Drupal - download
  - export DRUPAL_ROOT=/var/www/drupal
  - composer create-project
    drupal-composer/drupal-project:8.x-dev
    $DRUPAL_ROOT
    --stability dev
    --no-interaction
  - cd $DRUPAL_ROOT
  - composer require drupal/devel:~1.0

  # Drupal - install
  # Need '=' for options in Drush.
  - ./vendor/bin/drush site:install
    --db-url='mysql://drupal:${mysql_password}@localhost/drupal'
    --db-su=root
    --account-pass=${drupal_password}
  
  # Apache
  - a2enmod rewrite
  - a2ensite drupal
  - systemctl restart apache2
  

swap:
  filename: /swap.img
  size: ${swap_bytes}
  maxsize: ${swap_bytes_max}


write_files:
  - path: /etc/apache2/sites-available/drupal.conf
    permissions: '0644'
    content: |
      Listen 8080
      <VirtualHost *:8080>
        DocumentRoot /var/www/drupal/web
        <Directory /var/www/drupal/web>
          AllowOverride all
        </Directory>
        ErrorLog $${APACHE_LOG_DIR}/drupal_error.log
        CustomLog $${APACHE_LOG_DIR}/drupal_access.log combined
      </VirtualHost>
