#cloud-config
apt:
  # Add PHP/Apache sources.
  sources:
    source1:
      source: 'ppa:ondrej/php'
    source2:
      source: 'ppa:ondrej/apache2'

packages:
  # Lamp
  - apache2
  - apache2-bin
  - lamp-server^

  # Dev tools
  - composer
  - git

  # PHP extensions
  - php${php_ver}-curl
  - php${php_ver}-gd
  - php${php_ver}-mbstring
  - php${php_ver}-mysql
  - php${php_ver}-xml
  - php${php_ver}-zip

runcmd:
  # Change swappiness
  - echo 'vm.swappiness=10' >> /etc/sysctl.conf
  # Composer
  - export HOME=/root
  - composer global require consolidation/cgr
  - echo PATH="$(composer global config home)/vendor/bin:$PATH" >> ~/.bashrc
  - . ~/.bashrc
  # Drush
  - cgr drush/drush
  # MySQL setup
  # - mysql -e 'CREATE DATABASE drupal'
  # - mysql -e 'GRANT ALL PRIVILEGES ON drupal.* TO drupal@localhost IDENTIFIED BY '\''${mysql_password}'\'

  # Drupal - download
  - export DRUPAL_ROOT=/var/www/drupal
  - composer create-project
    drupal-composer/drupal-project:8.x-dev
    $DRUPAL_ROOT
    --stability dev
    --no-interaction
  - cd $DRUPAL_ROOT
  - composer require drupal/devel:~1.0

  # Drupal - install
  - drush site:install
    --db-url 'mysql://root@localhost/drupal'
    --account-name root
    --account-pass ${drupal_password}
  
  # Apache
  - a2enmod rewrite
  - a2ensite drupal
  - systemctl restart apache2
  

swap:
  filename: /swap.img
  size: ${swap_bytes}
  maxsize: ${swap_bytes_max}


write_files:
  - path: /etc/apache2/sites-available/drupal.conf
    permissions: '0644'
    content: |
      Listen 8080
      <VirtualHost *:8080>
        DocumentRoot /var/www/drupal/web
        <Directory /var/www/drupal/web>
          AllowOverride all
        </Directory>
        ErrorLog $${APACHE_LOG_DIR}/drupal_error.log
        CustomLog $${APACHE_LOG_DIR}/drupal_access.log combined
      </VirtualHost>
